### ISSUE TITLE
onHover is called but not onDrop is not called when drag&drop something from another browser tab

### ISSUE THREAD

**Issue by krillefear** [deakjahn/flutter_dropzone#19]
Steps to reproduce:
1. Open another browser window
2. Open an image in this window
3. Drag&drop this image to the flutter dropzone
4. onHover is triggered but not onDrop

We should either make sure that onHover is not triggered then or make it possible that onDrop gets the url of the image.

**Comment by deakjahn** [comment]
[I"ve just checked, I _am_ watching this repo, still I didn't receive a notification. Go figure. Sorry.]

Basically, the plugin is just a wrapper around the HTML Drag & Drop functionality, so it can only provide what the browser itself provides. Besides, even within the same browser tag, we actively check for file drops in the `flutter_dropzone.js` line of

    var match = (item.kind === 'file');

because this is our primary goal. You might want to experiment with this but even then, I don't think you'll get cross-tab support from your browser.
