### ISSUE TITLE
DropzoneView

### ISSUE THREAD

**Issue by gowthamk17** [deakjahn/flutter_dropzone#28]
i'm only run the project in web but it says DropzoneView: TargetPlatform.linux does not support
![Screenshot from 2021-06-15 13-18-55](https://user-images.githubusercontent.com/51103345/122013910-450e5b00-cddc-11eb-9ec8-181f8f4ca5d6.png)

**Comment by deakjahn** [comment]
Than won't be enough for me to determine what's wrong with your setup. :-)

The message comes from `MethodChannelFlutterDropzone`. Check the functions there, all throw this exception. They are only called if it's not the web version that's running. Try to determine which of them is giving the message (you might want to customize the error messages in order to see).

You need to put breakpoints in the code and see what happens. The scenario is as follows:

`FlutterDropzonePlatform` has an `_instance` that's initalized to the `MethodChannelFlutterDropzone` mentioned above:
https://github.com/deakjahn/flutter_dropzone/blob/cf70c12174d9042ef74e48e512c4e0b24baea549/flutter_dropzone_platform_interface/lib/flutter_dropzone_platform_interface.dart#L18

However, this has to be overridden when you start the web plugin:
https://github.com/deakjahn/flutter_dropzone/blob/cf70c12174d9042ef74e48e512c4e0b24baea549/flutter_dropzone_web/lib/flutter_dropzone_plugin.dart#L20-L26

And this is actually called from the automatically generated file:
https://github.com/deakjahn/flutter_dropzone/blob/cf70c12174d9042ef74e48e512c4e0b24baea549/flutter_dropzone/example/lib/generated_plugin_registrant.dart#L12-L15

So, as a shot in the dark, I suspect some problems with the generation and execution of this file at your end.
