### ISSUE TITLE
How to remove message "Height of Platform/Width of Platform"

### ISSUE THREAD

**Issue by NickKoroloff** [deakjahn/flutter_dropzone#29]
Hello, i updated flutter to v.2.5, and now receive messages in console, how to fix it?)
Height of Platform View type: [com.creativephotocloud.plugins/dropzone] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [com.creativephotocloud.plugins/dropzone] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

**Comment by deakjahn** [comment]
Considering that something like this has been added recently: https://github.com/deakjahn/flutter_dropzone/commit/b6cdeccbe3c182093630242354591f9a20eb5305

Well, I don't know... Maybe I haven't yet pushed it to Pub.dev?

**Comment by deakjahn** [comment]
Could you check the 2.0.4 (web) version that I published now?

**Comment by lrmoorejr** [comment]
> Could you check the 2.0.4 (web) version that I published now?

I'm seeing the same issue, but using flutter_dropzone 2.0.1 as I have multiple platform targets.  Do I need a 2.0.4 release of flutter_dropzone to get this fix?  2.0.1 is the most recent version that flutter pub get allows.

**Comment by NickKoroloff** [comment]
> Could you check the 2.0.4 (web) version that I published now?

in pub dev last version 2.0.1 , how I can update it to 2.0.4?

**Comment by deakjahn** [comment]
If you just upgrade the usual way (`flutter pub upgrade`), you should receive the latest automatically. No matter what's in your pubspec, the system always downloads the latest from the same major version (but it doesn't jump to a new major version).

If you want to check out what you have, just go into _SDK\flutter\.pub-cache\hosted\pub.dartlang.org_ wherever you keep your Flutter SDK (this path comes from a Windows machine, I don't know if it's exactly the same on other platforms) and see what versions you have. Yoz don't need to, but I sometimes delete very old versions of various plugins from this folder manually because it can grow to quite some size. A pity the framework doesn't offer a purge command itself. :-)

**Comment by deakjahn** [comment]
@lrmoorejr The main plugin is 2.0.1 but this is a federated plugin, meaning the apart from the main one, there are two other dependent ones (the `platform_interface` and the `_web`). The second one was upgraded.

As I wrote to Nick, you don't have to worry about the differences. If you upgrade your pub the usual way, you get the latest from the dependent packages as well.

**Comment by NickKoroloff** [comment]
@deakjahn Big thx to you,now it works well without console messages !!) we can close the issue!

**Comment by lrmoorejr** [comment]
Also confirmed that it worked.  Thanks for the fix and the tips!
