### ISSUE TITLE
How about large files?

### ISSUE THREAD

**Issue by Wissperwind** [deakjahn/flutter_dropzone#40]
Hi,

What is the best way to handle large files?
`Future<Uint8List> getFileData(dynamic htmlFile);` seems to load the whole file in memory. That is not possible if someone drops a 8GB file. Is there an option to get a stream like reference?

**Comment by deakjahn** [comment]
No. A package like this can only do what the underlying browser (and the specifications governing them) allows. File handling is very intentionally limited there and, due to security implications, very unlikely to be changed significantly ever.

If you're OK with the link only available during the session, use the temporary link approach. If you need to save the data, there's no other way. Besides, there are browser limitations on how much data you can store, so you're not likely to get away with using it to store inordinate amounts, I guess...

**Comment by Wissperwind** [comment]
But browsers in general are able to upload 8GB files. That's not the problem.
It is just necessary to upload a file without loading it in memory completely befire starting the transfer to the server.
