### ISSUE TITLE
Missing tag on GitHub

### ISSUE THREAD

**Issue by franzlst** [deakjahn/flutter_dropzone#70]
We are using [ort](https://github.com/oss-review-toolkit/ort/) for automatic software compliance checks.

flutter_dropzone is one of our dependencies and we use it in version 3.0.6. Now, ort fails in scanning this repo, as this version is not tagged on GitHub.

Could you please add the missing tag "3.0.6" to GitHub and keep these tags in sync with upcoming releases?

**Comment by deakjahn** [comment]
A bit unwillingly because I use many various platforms and various IDEs and all handle this task differently -- and I'm liable to forget it the next time around, anyway :-). Besides, Pub.dev being the primary source for Flutter plugins, I don't even really understand why your software looks for it on GitHub...

**Comment by franzlst** [comment]
>  Besides, Pub.dev being the primary source for Flutter plugins, I don't even really understand why your software looks for it on GitHub...

This is just what I thought, which is why I also opened a ticket on the tool side.

Nevertheless, adding the tag here helped me in the short-thank, which is why I thank you a lot!
