### ISSUE TITLE
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.

### ISSUE THREAD

**Issue by tushar0518** [deakjahn/flutter_dropzone#73]
I'm getting the below warning when using the dropzone package. @deakjahn 

**Warnings**:
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web`
instead.
The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from
`dart:ui_web` instead.

Possible Fix: change this import => `import 'dart:ui' as ui;`  to `import 'dart:ui_web' as ui;` throughout the project

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 13.3 22E252 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)

**Comment by JorgeBrandao1980** [comment]
Good morning. 
I have exactly the same problem, have you found a solution yet? 
Thank you.

**Comment by tushar0518** [comment]
> Good morning. I have exactly the same problem, have you found a solution yet? Thank you.

not at the moment, if only the author of the plugin should make the changes and release a new version.

**Comment by deakjahn** [comment]
@tushar0518 Yes, yes, I hear. But this is always a double edged sword. Flutter introduces something new and deprecates the old one. People who upgrade their Flutter immediately are annoyed by the warning. But other people who don't upgrade might find their existing, functioning plugins suddenly broken. It's always a tough decision to determine how long to wait. Now that we moved, we might get an influx of angry people reporting that the plugin no longer works for them just because they still use a Flutter version of a year ago. :-))

**Comment by ztaylor54** [comment]
> <...> we might get an influx of angry people reporting that the plugin no longer works for them just because they still use a Flutter version of a year ago. :-))

@deakjahn here with my pitchfork 😅

This is a non-issue with proper use of [version constraints](https://dart.dev/tools/pub/dependencies#version-constraints) in your pubspec.yaml. At the very least, it should be a new major version, which would indicate a breaking change and prevent a `flutter pub upgrade` from upgrading versions automatically (hence why I'm here). See [this stack overflow answer](https://stackoverflow.com/a/66201338) for more context / info.

The [release notes for 3.13.0](https://docs.flutter.dev/release/release-notes/release-notes-3.13.0) show the [addition of the deprecation message to the `dart:ui` package](https://github.com/flutter/engine/pull/41877), so you'd probably be OK updating the pubcpec.yaml with: 

```
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.13.0"
```

The temporary workaround on my end (and for anyone else who comes across this) is to override the version for `flutter_dropzone_web` in pubspec.yaml:

```
dependency_overrides:
  flutter_dropzone_web: <=3.0.12
```

or upgrade to a version of flutter >= 3.13.

**Comment by ztaylor54** [comment]
@deakjahn I would agree if it were just a deprecation - but your change depends on `dart:ui_web`:

https://github.com/deakjahn/flutter_dropzone/blob/feb34bdc20165ec9eadba6ae11737bcfd03512e1/flutter_dropzone_web/lib/flutter_dropzone_plugin.dart#L3

`dart:ui_web` was introduced in Flutter version `3.10.0` (see the [release notes](https://docs.flutter.dev/release/release-notes/release-notes-3.10.0) and [PR](https://github.com/flutter/engine/pull/40608)) and `platformViewRegistry` wasn't moved into `ui_web` until version `3.13.0` (see my above comment), but the `pubspec.yaml` only requires `>=1.17.0`:

https://github.com/deakjahn/flutter_dropzone/blob/feb34bdc20165ec9eadba6ae11737bcfd03512e1/flutter_dropzone_web/pubspec.yaml#L8

This ___is___ a breaking / major change if you don't keep your version constraints up-to-date. In fact, this package is currently broken for any news users that don't have at least flutter version `3.13.0` installed. It causes the following compilation error:

```
../../../../.pub-cache/hosted/pub.dev/flutter_dropzone_web-3.0.13/lib/flutter_dropzone_plugin.dart:27:8: Error: Undefined name 'platformViewRegistry'.
    ui.platformViewRegistry.registerViewFactory(
       ^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_dropzone_web-3.0.13/lib/flutter_dropzone_plugin.dart:33:26: Error: Undefined name 'assetManager'.
    final scriptUrl = ui.assetManager.getAssetUrl(
```

You should _at the very least_ update the `pubspec.yaml` to include the proper constraints in the next release.

**Comment by deakjahn** [comment]
@ztaylor54 I added it. The reason I'm a bit unwilling to make it a breaking change now is that a new version is in the works (see https://github.com/deakjahn/flutter_dropzone/pull/76) that we're forced to do, anyway, because of underlying changes in Flutter. And that will be a breaking change and a new major version for sure. Unfortunately for us, Flutter is doing very active work in this department now and this makes it a bit of a moving target. Also, I have the feeling that this new approach with the `web` package in not as mature yet as the Flutter team makes it out to be. I'm afraid we'll have some serious bumps on this road, no matter what.
