### ISSUE TITLE
Where can i find all Mime type?

### ISSUE THREAD

**Issue by Trung15010802** [deakjahn/flutter_dropzone#87]
What MIME types does this package support?

**Comment by deakjahn** [comment]
The package is totally uninterested in MIME types, it just passes it along to the browser. All that the standard seems to say about this is that if the actual MIME type is known, it should be used, otherwise it will be `application/octet-stream`. See https://html.spec.whatwg.org/multipage/dnd.html#drag-and-drop-processing-model
